version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py
  deployment:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "Deployment file running..."

workflows:
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deployment:
          requires:
            - test
          filters:
            branches:
              only: main